openapi: 3.0.3
info:
  title: User Permissions API
  description: API for managing user permissions and access control
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:3000/v1
    description: Local development server

paths:
  /users:
    get:
      summary: List all users
      description: Retrieve a paginated list of all users in the system
      operationId: listUsers
      tags:
        - Users
      parameters:
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/OffsetParam'
      responses:
        '200':
          description: Successfully retrieved list of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserList'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

  /users/{userId}:
    delete:
      summary: Delete a user
      description: Remove a user from the system
      operationId: deleteUser
      tags:
        - Users
      parameters:
        - $ref: '#/components/parameters/UserIdParam'
      responses:
        '204':
          description: User successfully deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

  /users/{userId}/permissions:
    get:
      summary: Get user permissions
      description: Retrieve all permissions assigned to a specific user
      operationId: getUserPermissions
      tags:
        - User Permissions
      parameters:
        - $ref: '#/components/parameters/UserIdParam'
      responses:
        '200':
          description: Successfully retrieved user permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPermissions'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

    put:
      summary: Update user permissions
      description: Replace all permissions for a specific user
      operationId: updateUserPermissions
      tags:
        - User Permissions
      parameters:
        - $ref: '#/components/parameters/UserIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PermissionRequest'
      responses:
        '200':
          description: Successfully updated user permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPermissions'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

    post:
      summary: Add permissions to user
      description: Add new permissions to a specific user without removing existing ones
      operationId: addUserPermissions
      tags:
        - User Permissions
      parameters:
        - $ref: '#/components/parameters/UserIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PermissionRequest'
      responses:
        '201':
          description: Successfully added permissions to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPermissions'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

  /permissions:
    get:
      summary: List all permissions
      description: Retrieve a list of all available permissions in the system
      operationId: listPermissions
      tags:
        - Permissions
      parameters:
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/OffsetParam'
      responses:
        '200':
          description: Successfully retrieved list of permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PermissionsList'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  schemas:
    UserId:
      type: string
      description: Unique identifier for a user
      example: "user-123"
      minLength: 1
      maxLength: 128

    PermissionId:
      type: string
      description: Unique identifier for a permission
      example: "perm-read-users"
      minLength: 1
      maxLength: 128

    LimitInteger:
      type: integer
      description: Maximum number of items to return
      minimum: 1
      maximum: 100
      default: 20

    OffsetInteger:
      type: integer
      description: Number of items to skip for pagination
      minimum: 0
      default: 0

    User:
      type: object
      description: Represents a user in the system
      properties:
        id:
          $ref: '#/components/schemas/UserId'
        name:
          type: string
          description: Full name of the user
          example: "John Doe"
          minLength: 1
          maxLength: 256
        email:
          type: string
          format: email
          description: Email address of the user
          example: "john.doe@example.com"
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the user was created
          example: "2024-01-15T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the user was last updated
          example: "2024-01-20T14:45:00Z"
      required:
        - id
        - name
        - email

    UserList:
      type: object
      description: Paginated list of users
      properties:
        users:
          type: array
          description: Array of user objects
          items:
            $ref: '#/components/schemas/User'
        total:
          type: integer
          description: Total number of users available
          example: 150
          minimum: 0
        limit:
          type: integer
          description: Maximum number of users returned
          example: 20
          minimum: 1
        offset:
          type: integer
          description: Number of users skipped
          example: 0
          minimum: 0
      required:
        - users
        - total

    Permission:
      type: object
      description: Represents a permission in the system
      properties:
        id:
          $ref: '#/components/schemas/PermissionId'
        name:
          type: string
          description: Human-readable name of the permission
          example: "Read Users"
          minLength: 1
          maxLength: 128
        description:
          type: string
          description: Detailed description of what this permission allows
          example: "Allows reading user information"
          maxLength: 512
        category:
          type: string
          description: Category grouping for the permission
          example: "users"
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the permission was created
          example: "2024-01-01T00:00:00Z"
      required:
        - id
        - name

    PermissionsList:
      type: object
      description: Paginated list of permissions
      properties:
        permissions:
          type: array
          description: Array of permission objects
          items:
            $ref: '#/components/schemas/Permission'
        total:
          type: integer
          description: Total number of permissions available
          example: 25
          minimum: 0
        limit:
          type: integer
          description: Maximum number of permissions returned
          example: 20
          minimum: 1
        offset:
          type: integer
          description: Number of permissions skipped
          example: 0
          minimum: 0
      required:
        - permissions
        - total

    UserPermissions:
      type: object
      description: Permissions assigned to a specific user
      properties:
        userId:
          $ref: '#/components/schemas/UserId'
        permissions:
          type: array
          description: Array of permissions assigned to the user
          items:
            $ref: '#/components/schemas/Permission'
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when permissions were last modified
          example: "2024-01-20T14:45:00Z"
      required:
        - userId
        - permissions

    PermissionRequest:
      type: object
      description: Request body for adding or updating permissions
      properties:
        permissionIds:
          type: array
          description: Array of permission IDs to assign
          items:
            $ref: '#/components/schemas/PermissionId'
          minItems: 1
          uniqueItems: true
      required:
        - permissionIds

    Error:
      type: object
      description: Standard error response
      properties:
        code:
          type: string
          description: Error code for programmatic handling
          example: "VALIDATION_ERROR"
        message:
          type: string
          description: Human-readable error message
          example: "The request body is invalid"
        details:
          type: array
          description: Additional error details
          items:
            $ref: '#/components/schemas/ErrorDetail'
      required:
        - code
        - message

    ErrorDetail:
      type: object
      description: Detailed information about a specific error
      properties:
        field:
          type: string
          description: The field that caused the error
          example: "permissionIds"
        reason:
          type: string
          description: Reason for the error
          example: "must not be empty"
      required:
        - field
        - reason

  parameters:
    UserIdParam:
      name: userId
      in: path
      required: true
      description: Unique identifier of the user
      schema:
        $ref: '#/components/schemas/UserId'

    LimitParam:
      name: limit
      in: query
      required: false
      description: Maximum number of items to return
      schema:
        $ref: '#/components/schemas/LimitInteger'

    OffsetParam:
      name: offset
      in: query
      required: false
      description: Number of items to skip for pagination
      schema:
        $ref: '#/components/schemas/OffsetInteger'

  responses:
    BadRequest:
      description: Bad request - invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Unauthorized:
      description: Unauthorized - authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token authentication

security:
  - BearerAuth: []

tags:
  - name: Users
    description: User management operations
  - name: User Permissions
    description: Operations for managing user permissions
  - name: Permissions
    description: Permission catalog operations